### ISSUE TITLE
Looks cool - Is Basic auth support broken

### ISSUE THREAD

**Issue by gmcinnes** [solutious/stella#1]
Trying to use basic auth doesn't work for me.

I notice your basic auth examples are commented out too. Is it broken?

**Comment by delano** [comment]
Nope, not broken! I just didn't need them for that example.

**Comment by gmcinnes** [comment]
Maybe I'm not using it correctly.

Here's my test plan: 

<pre>

USERNAME = 'test3'
PASSWORD = 'test3'

usecase "Getting a patient list" do
auth USERNAME, PASSWORD
  get '/v1/patients' do
    response 200 do
    end
  end
end

</pre>


And here's what I see as the Rack environment that my Sinatra app is passed.  

<pre>

    {"GATEWAY_INTERFACE"=>"CGI/1.1", 
"PATH_INFO"=>"/v1/patients",
"QUERY_STRING"=>"", 
"REMOTE_ADDR"=>"127.0.0.1",
 "REMOTE_HOST"=>"localhost", 
"REQUEST_METHOD"=>"GET",
 "REQUEST_URI"=>"http://localhost:9292/v1/patients",
 "SCRIPT_NAME"=>"",
 "SERVER_NAME"=>"localhost", 
"SERVER_PORT"=>"9292", 
"SERVER_PROTOCOL"=>"HTTP/1.1",
 "SERVER_SOFTWARE"=>"WEBrick/1.3.1 (Ruby/1.9.2/2010-12-25)", 
"HTTP_USER_AGENT"=>"Stella/0.8.7", 
"HTTP_DATE"=>"Fri, 25 Feb 2011 21:04:14 GMT",
 "HTTP_HOST"=>"localhost:9292", 
"rack.version"=>[1, 1],
 "rack.input"=>#<StringIO:0x000001015450e0>, 
"rack.errors"=>#<IO:<STDERR>>,
 "rack.multithread"=>true, 
"rack.multiprocess"=>false,
 "rack.run_once"=>false,
 "rack.url_scheme"=>"http", 
"HTTP_VERSION"=>"HTTP/1.1", 
"REQUEST_PATH"=>"/", 
"rack.request.query_string"=>"",
 "rack.request.query_hash"=>{}}

</pre>


I don't see HTTP_AUTHORIZATION environment variables being set.  Any ideas?

**Comment by delano** [comment]
Crap, my bad. I changed the param name to `http_auth`. I'll update that config example now. 

Try:

```
usecase "Getting a patient list" do
  http_auth USERNAME, PASSWORD
  get '/v1/patients' do
    response 200 do
    end
  end
end
```

**Comment by gmcinnes** [comment]
Yeah, I spent a while looking at the code and setting debuggers here and there, and I'd already tried that.   Here's what happens:

<pre>

$ stella verify -p patient_list.rb http://localhost:9292
ERROR (ArgumentError): wrong number of arguments (2 for 0)
ruby(17283,0x7fff701d0ca0) malloc: *** error for object 0x100400000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap

</pre>


I think the abort trap may be a red herring.  That happens whenever it needs to exit abnormally for any reason: 

<pre>

$ stella foo
Unknown command: foo
ruby(17304,0x7fff701d0ca0) malloc: *** error for object 0x100400000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap

</pre>

**Comment by delano** [comment]
Are you using Ruby 1.9.2p136 by chance? That looks like this bug which is fixed:
http://redmine.ruby-lang.org/issues/show/4389

That bug originates from a dependency lib called benelux. There's a fix in the 0.6.1 release.

```
gem install benelux --version 0.6.1
```

_Edit_: Redmine is down, here's [another link](http://fossplanet.com/f14/[ruby-core-35192]-[ruby-1-9-bug-4389][open]-pointer-being-freed-not-allocated-error-after-setting-instance-variable-metaclass-thread-current-103738/).

**Comment by gmcinnes** [comment]
hmm. ok:

http_auth(USERNAME, PASSWORD) still says: wrong number of arguments

auth(USERNAME, PASSWORD) works, but still produces the rack env above on the server.

I'm using bundler, so I set my Gemfile to force version 0.6.1 for Benelux, but 

Bundler could not find compatible versions for gem "benelux":
  In Gemfile:
    stella (= 0.8.7.003) depends on
      benelux (= 0.5.15)

```
benelux (0.6.1)
```

But I'm still think the Abort Trap stuff might be a red herring.

**Comment by delano** [comment]
Okay, looks like something is up. I'll get to the bottom of it over the weekend. 

Thanks for your patience.

**Comment by delano** [comment]
Problem solved. I pushed a new release, Stella 0.8.8, which includes a proper HTTP auth example and requires Benelux 0.5.17. 

See:
https://github.com/solutious/stella/blob/master/examples/httpauth/plan.rb

Note that I was incorrect earlier when I suggested `http_auth`. The documentation was correct.

**Comment by gmcinnes** [comment]
Ok.  I see your httpauth example is working, but my usecase still isn't.

I haven't had time to totally isolate it into it, but it seems that under the hood httpclient mimics the behaviour of a browser, first hitting the page without auth credentials, then retrying with auth credentials on receipt of a 401 (mimicking how a browser would pop up a modal box for users.  For some reason, which I don't understand, this doesn't happen with my usecase.

**Comment by delano** [comment]
Could you post a (sanitized) copy of your server config for the authentication?

**Comment by gmcinnes** [comment]
<pre>
before do
  @auth ||= Rack::Auth::Basic::Request.new(request.env)
  begin
    authorized = @auth.credentials == ['test3', 'test3']
    halt 401, 'Not authorized' unless authorized
  rescue
    halt 401, 'Not authorized' unless authorized
  end
end

get '/login' do
end
</pre>


<pre>
require 'rubygems'
require 'sinatra'
require './test'
run Sinatra::Application
</pre>


<pre>
usecase "Use basic HTTP authentication" do
  auth 'test3', 'test3'

  get '/login' do
    response 401 do
      puts "rejected"
    end

    response 200 do
      puts "logged in"
    end
  end
end
</pre>

**Comment by gmcinnes** [comment]
Solved!  I need to send back the 'WWW-Authenticate' header along with 401 Not Authorized in order to get httpclient to retry with authentication.

There's probably a spec somewhere that says I'm supposed to do that :)

**Comment by delano** [comment]
Great, glad it's working!
